os: linux
version: 0.0
files:
  - source: app.js
    destination: /opt/unicorn

  - source: package.json
    destination: /opt/unicorn

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
